### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by DiaSird** [kelpsyberry/dust#2]
We faced [the below build error](https://github.com/Thoughts-with-friends/custom_dust/actions/runs/6971830542/job/18972710760) in your code. You may need to specify [a revision](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) or distribute Cargo.lock.

<img width="650" alt="image" src="https://github.com/kelpsyberry/dust/assets/78157340/154cca58-11fd-4507-80b3-c06e0e720340">

**Comment by kelpsyberry** [comment]
Does commit 25e3081d27e7ca6a0631187709dbaed59205e140 fix the issue?
