### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kojq** [kelpsyberry/dust#3]
I want to try making a PKGBUILD for the AUR. Build instructions could be helpful. Also, the name `dust` is already taken. Not sure how to handle that aspect.

**Comment by kojq** [comment]
I could do `dust-emu` to keep the `dust` name.

**Comment by kelpsyberry** [comment]
From a discussion in private:
- `dust-emu` is preferred, `dust-ds` is used for the website temporarily
- I'll add documentation, but the emulator's desktop frontend can be built as a normal rust crate with `cargo build`, specifically:
    - `cargo build --release --package dust-desktop` for a "local" release build with debug info (usable for debugging, since the debug build is too slow to be usable)
    - `cargo build --profile ci --package dust-desktop` for a release build with maximal optimization and no debug info (which is what the CI builds and the AUR -git package will use)
- The desktop frontend will be published to the AUR as `dust-emu-git`
